// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: FrameSync.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace FrameSync
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerInput : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"player_id")]
        public int PlayerId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"target_frame")]
        public int TargetFrame { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"input_x")]
        public float InputX { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"input_y")]
        public float InputY { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"jump")]
        public bool Jump { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FrameInput : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"frame_number")]
        public int FrameNumber { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"inputs")]
        public global::System.Collections.Generic.List<PlayerInput> Inputs { get; } = new global::System.Collections.Generic.List<PlayerInput>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StateHash : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"player_id")]
        public int PlayerId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"frame_number")]
        public int FrameNumber { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"hash")]
        public int Hash { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
